var env={
   DISCOVERY_USERNAME:'37a20a37-c183-48b5-86b1-d3751a028e90',
   DISCOVERY_PASSWORD:'vGp6gzcOVrT2',
   TONE_USERNAME:'b064be0e-5052-4aeb-9d91-d3d0863b374f',
   TONE_PASSWORD:'kpcsS5mlTh8X',
   //FACEBOOCK_TOKEN:'EAAK1XNUezSkBALGZBTrmmI2nuvheW2RFUJBNMZAqHwJQienwymX21vZBZBR2ZBvZC39LkmVtuLVa4gztZA4t7MRfKvP9crASnKnte2hwgDISAtZBqRwKUfQMaBvOxHpZCmZAi3LULGchuocxzym9e8xrlvxQlO4LOjPeivqZCBcj6ZCGzV4UZB9CUiZAZCm',
   FACEBOOCK_TOKEN:'EAACVzkWiWzMBAMBzPfokhIhZAI2bMIJGZCgqh9o1EiwOcc1yyDgwsuDqpUhPcvUt9btNMYNEZCegmiomTHEpzzF3XYBB8Ej8vhXJlftGD83ll4e0URRj8jJWzpELZC0R7tE16jyZCI2CgR8sXSnejoMriM6hHr5jEY5ctDSHRrCPgQAwaHWH2',
   /*HOST_MYSL:'sl-us-south-1-portal.5.dblayer.com',
    PORT_MSQL:'19734',
    USER_MYSQL:'admin',
    PASS_MYSQL:'LYJPXDLLBNCZQRFM',
    DATABE_MYSQL:'analizercomment',*/
   // HOST_MYSL:'localhost',
   // PORT_MSQL:'3306',
   // USER_MYSQL:'root',
   // PASS_MYSQL:'root',
   // DATABE_MYSQL:'cb_intranet',
    PGUSER:'postgres',
    PGHOST:'localhost',
    PGPASSWORD:'123',
    PGDATABASE:'produccion_intranet',
    PGPORT:'5433',
   KEY_ENCRYPT:'SMA_CLOUDBIT_SRL_FACEBBOK_ANALIZAERTONE_WATSON',
   SECRET_TOKEN:'SMA_VERIF_NEW_USER_CLOUDBIT_SRL_FACEBOOK_ANALIZAERTONE_WATSON'
}
module.exports=env;